### ISSUE TITLE
Move to adopted-ember-addons

### ISSUE THREAD

**Issue by cowboyd** [adopted-ember-addons/emberx-file-input#65]
# Addon Transfer Checklist
These are the things that need to done to transfer your addon: 
- [x] Update the package.json repository field to point to the new location
- [x] If any demo URL or homepage is referenced, it should be updated. At the very least, file an issue on the repo so the adopter can fix
- [x] Ensure Release practices are documented
- [x] Add `adopted-ember-addons` to the maintainers of the package on `npm`. Remove other maintainers.

**Comment by trek** [comment]
@cowboyd I think there's one final step remaining? (transfer to @MelSumner so she can transfer to the org?).

**Comment by cowboyd** [comment]
It looks like it's just waiting to be accepted 👍🏻 

![image](https://user-images.githubusercontent.com/4205/117272998-62a6e700-ae64-11eb-8749-5b4a76079ac7.png)

**Comment by trek** [comment]
@cowboyd could you Abort and retry? It looks like the invite expired.

**Comment by cowboyd** [comment]
Done!

**Comment by MelSumner** [comment]
Hi! So sorry but it already expired again. Could you try one more time and ping me on Discord so I can take care of it immediately? Apologies for the inconvenience. 

Melanie Sumner
Senior Software Engineer
GitHub: melsumner
(312) 982-1554

**Comment by cowboyd** [comment]
@MelSumner you bet :)
